from futu import TrdEnv

FUTU_OPEN_D_HOST = '127.0.0.1'
FUTU_OPEN_D_PORT = 11111
FUTU_TRADE_PWD = '963527' # Use in real environment
FUTU_ENV = TrdEnv.REAL # Switch to REAL, for real trade
DEFAULT_TRADING_CURRENCY = "USD"
SHARES_ORDER_PERCENTAGE_PER_STOCK = 0.25
OPTION_MAX_PER_TYPE = 3
OPTION_CALL_INDEX = 2
OPTION_PUT_INDEX = 2
OPTION_QTY_PER_ORDER = 1
TRADE_EXPIRY_OPTION = False
ALLOW_MULTIPLE_ORDER_PER_DIRECTION = True # Allow multiple orders per direction
API_QUEUE_DELAY = 1